/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.teko;

import java.io.File;
import java.io.IOException;
import java.util.ResourceBundle.Control;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application{
    
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {

        primaryStage.setTitle("Rail Traffic");
        try {
            File fxmlFile = new File ("./src/main/java/ch/teko/RailTrafficView.fxml");
            FXMLLoader loader = new FXMLLoader(fxmlFile.toURI().toURL());
            Parent root = loader.load();
            Controller controller = (Controller)loader.getController();
            controller.makeRequest();
            Scene scene = new Scene(root);
            primaryStage.setScene(scene);
            primaryStage.show();
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }

    }


}
